/*
 *
 * Projeto (projeto_lp2_1516) - Linguagens de Programaçao 2
 * 
 * edu.ufp.inf.lp2.project.gui
 * AppMainJFrame.java
 *
 * 2015/2016 (c) Universidade Fernando Pessoa
 *
 */
package edu.ufp.inf.lp2.project.gui;

import edu.ufp.inf.lp2.project.AppMain;
import edu.ufp.inf.lp2.project.Connection;
import edu.ufp.inf.lp2.project.Coordinate;
import edu.ufp.inf.lp2.project.Line;
import edu.ufp.inf.lp2.project.Network;
import edu.ufp.inf.lp2.project.Passenger;
import edu.ufp.inf.lp2.project.Station;
import edu.ufp.inf.lp2.project.UsefullFunctions;
import java.awt.Dialog;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tiagocardoso
 */
public class AppMainJFrame extends javax.swing.JFrame {

    private static final boolean SAVE_BINARY = false;
    protected static Network network;
    private Vector cb_stations = new Vector();
    /**
     * Creates new form AppMainJFrame
     */
    public AppMainJFrame() {
        ArrayList<String> lines = new ArrayList<>();
        lines.add("a");
        lines.add("b");
        lines.add("c");
        lines.add("d");
        lines.add("e");
        lines.add("f");
        
        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(new File(".//data//network_2s.txt")));
            int V = Integer.parseInt(br.readLine());
            System.out.println("V = " + V);
            this.network = new Network(V);
            int E = Integer.parseInt(br.readLine());
            System.out.println("E = " + E);
            
            String line = br.readLine();
            while(line!= null) {
                StringTokenizer st = new StringTokenizer(line);
                int v = Integer.parseInt(st.nextToken());
                int w = Integer.parseInt(st.nextToken());
                
                double c1 = Double.parseDouble(st.nextToken());
                double c2 = Double.parseDouble(st.nextToken());
                double c3 = Double.parseDouble(st.nextToken());
                
                this.network.addEdge(new Connection(v,w,c1,c2,c3));
                
                line = br.readLine();
            }
            
            System.out.println(this.network.toString());
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AppMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AppMain.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                br.close();
            } catch (IOException ex) {
                Logger.getLogger(AppMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(!SAVE_BINARY) {
            this.network.loadStations(".//data//stations.txt",0);
        } else {
            this.network.loadStations(".//data//binary//stations.txt",1);
        }
        this.network.loadLines(lines);
       
        initComponents();
        
        
        for (Integer id : this.network.getStationsST().keys()) {
            Station s = this.network.getStationsST().get(id);
            this.cb_stations.addElement(new Item(s.getId(), s.getName()));
        }
 
        jComboBoxStations.setModel(new DefaultComboBoxModel(cb_stations));
        jcbConnectionS1.setModel(new DefaultComboBoxModel(cb_stations));
        jcbConnectionS2.setModel(new DefaultComboBoxModel(cb_stations));
        
        //initDisableComponents();
        jComboBoxPassengers.setEnabled(false);
        jButtonPassengersPrintConsole.setEnabled(false);
        jbSavePassengers.setEnabled(false);
        jButtonNearStation.setEnabled(false);
        jButtonPassengerEdit.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogNewPassenger = new javax.swing.JDialog();
        tfPassengerAddId = new javax.swing.JTextField();
        tfPassengerAddName = new javax.swing.JTextField();
        tfPassengerAddPosition = new javax.swing.JTextField();
        jButtonCreatePassenger = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfPassengerAddBirthdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfPassengerAddBalance = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jDialogEditPassenger = new javax.swing.JDialog();
        tfPassengerEditId = new javax.swing.JTextField();
        tfPassengerEditName = new javax.swing.JTextField();
        tfPassengerEditPosition = new javax.swing.JTextField();
        jButtonEditPassenger = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfPassengerEditBirthdate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfPassengerEditBalance = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jDialogStation = new javax.swing.JDialog();
        tfStationId = new javax.swing.JTextField();
        tfStationName = new javax.swing.JTextField();
        tfStationZone = new javax.swing.JTextField();
        tfStationPosition = new javax.swing.JTextField();
        jButtonStationAddEdit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        JTabbedPane = new javax.swing.JTabbedPane();
        jPanelApp = new javax.swing.JPanel();
        jPanelAppOptions = new javax.swing.JPanel();
        jbLoadPassengers = new javax.swing.JButton();
        jbSaveNetwork = new javax.swing.JButton();
        jPanelConnections = new javax.swing.JPanel();
        jPanelConnectionsAdd = new javax.swing.JPanel();
        jcbConnectionS1 = new javax.swing.JComboBox<>();
        jcbConnectionS2 = new javax.swing.JComboBox<>();
        jbConnectionAdd = new javax.swing.JButton();
        jbConnectionShortest = new javax.swing.JButton();
        jbConnectionPrice = new javax.swing.JButton();
        jcbConnectionPriceType = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanelStations = new javax.swing.JPanel();
        jPanelStationsOptions = new javax.swing.JPanel();
        jButtonStationsPrintConsole = new javax.swing.JButton();
        jbSaveStations = new javax.swing.JButton();
        jButtonNewStation = new javax.swing.JButton();
        jbStationLines = new javax.swing.JButton();
        jPanelStationsEdit = new javax.swing.JPanel();
        jButtonStationsEdit = new javax.swing.JButton();
        jComboBoxStations = new javax.swing.JComboBox<>();
        jPanelPassengers = new javax.swing.JPanel();
        jPanelPassengersOptions = new javax.swing.JPanel();
        jButtonPassengersPrintConsole = new javax.swing.JButton();
        jbSavePassengers = new javax.swing.JButton();
        jButtonNewPassenger = new javax.swing.JButton();
        jButtonNearStation = new javax.swing.JButton();
        jPanelPassengersEdit = new javax.swing.JPanel();
        jComboBoxPassengers = new javax.swing.JComboBox<>();
        jButtonPassengerEdit = new javax.swing.JButton();
        jPanelMap = new javax.swing.JPanel();
        drawPanel1 = new edu.ufp.inf.lp2.project.gui.DrawPanel();

        jDialogNewPassenger.setTitle("Create a new Passenger");
        jDialogNewPassenger.setAlwaysOnTop(true);
        jDialogNewPassenger.setResizable(false);
        jDialogNewPassenger.setSize(new java.awt.Dimension(612, 366));

        jButtonCreatePassenger.setText("Create");
        jButtonCreatePassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreatePassengerActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("Position:");

        jLabel3.setText("Name:");

        jLabel4.setText("Birthdate:");

        jLabel9.setText("Balance:");

        javax.swing.GroupLayout jDialogNewPassengerLayout = new javax.swing.GroupLayout(jDialogNewPassenger.getContentPane());
        jDialogNewPassenger.getContentPane().setLayout(jDialogNewPassengerLayout);
        jDialogNewPassengerLayout.setHorizontalGroup(
            jDialogNewPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewPassengerLayout.createSequentialGroup()
                .addGroup(jDialogNewPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogNewPassengerLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButtonCreatePassenger))
                    .addGroup(jDialogNewPassengerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDialogNewPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addGap(24, 24, 24)
                        .addGroup(jDialogNewPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPassengerAddBalance)
                            .addComponent(tfPassengerAddPosition)
                            .addComponent(tfPassengerAddName)
                            .addComponent(tfPassengerAddId, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(tfPassengerAddBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jDialogNewPassengerLayout.setVerticalGroup(
            jDialogNewPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogNewPassengerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jDialogNewPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassengerAddId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogNewPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassengerAddName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogNewPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassengerAddBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogNewPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassengerAddPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogNewPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassengerAddBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButtonCreatePassenger)
                .addGap(32, 32, 32))
        );

        jDialogEditPassenger.setTitle("Edit Passenger");
        jDialogEditPassenger.setAlwaysOnTop(true);
        jDialogEditPassenger.setResizable(false);
        jDialogEditPassenger.setSize(new java.awt.Dimension(612, 366));

        jButtonEditPassenger.setText("Save");
        jButtonEditPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditPassengerActionPerformed(evt);
            }
        });

        jLabel5.setText("ID:");

        jLabel6.setText("Position:");

        jLabel7.setText("Name:");

        jLabel8.setText("Birthdate:");

        jLabel10.setText("Balance:");

        javax.swing.GroupLayout jDialogEditPassengerLayout = new javax.swing.GroupLayout(jDialogEditPassenger.getContentPane());
        jDialogEditPassenger.getContentPane().setLayout(jDialogEditPassengerLayout);
        jDialogEditPassengerLayout.setHorizontalGroup(
            jDialogEditPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditPassengerLayout.createSequentialGroup()
                .addGroup(jDialogEditPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogEditPassengerLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButtonEditPassenger))
                    .addGroup(jDialogEditPassengerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDialogEditPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addGap(24, 24, 24)
                        .addGroup(jDialogEditPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPassengerEditPosition)
                            .addComponent(tfPassengerEditName)
                            .addComponent(tfPassengerEditId, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(tfPassengerEditBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPassengerEditBalance))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jDialogEditPassengerLayout.setVerticalGroup(
            jDialogEditPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogEditPassengerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jDialogEditPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassengerEditId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogEditPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassengerEditName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogEditPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassengerEditBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogEditPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassengerEditPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogEditPassengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassengerEditBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButtonEditPassenger)
                .addGap(32, 32, 32))
        );

        jDialogStation.setTitle("Create a new Passenger");
        jDialogStation.setAlwaysOnTop(true);
        jDialogStation.setResizable(false);
        jDialogStation.setSize(new java.awt.Dimension(612, 366));

        jButtonStationAddEdit.setText("Create");
        jButtonStationAddEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStationAddEditActionPerformed(evt);
            }
        });

        jLabel11.setText("ID:");

        jLabel12.setText("Position:");

        jLabel13.setText("Name:");

        jLabel14.setText("Zone");

        javax.swing.GroupLayout jDialogStationLayout = new javax.swing.GroupLayout(jDialogStation.getContentPane());
        jDialogStation.getContentPane().setLayout(jDialogStationLayout);
        jDialogStationLayout.setHorizontalGroup(
            jDialogStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogStationLayout.createSequentialGroup()
                .addGroup(jDialogStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogStationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDialogStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(24, 24, 24)
                        .addGroup(jDialogStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfStationPosition)
                            .addComponent(tfStationName)
                            .addComponent(tfStationId, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(tfStationZone, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDialogStationLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButtonStationAddEdit)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jDialogStationLayout.setVerticalGroup(
            jDialogStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogStationLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jDialogStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStationId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStationZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStationPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(33, 33, 33)
                .addComponent(jButtonStationAddEdit)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LP2 - Network ");

        jPanelAppOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        jbLoadPassengers.setText("Load Passengers");
        jbLoadPassengers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoadPassengersActionPerformed(evt);
            }
        });

        jbSaveNetwork.setText("Save Network");
        jbSaveNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveNetworkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAppOptionsLayout = new javax.swing.GroupLayout(jPanelAppOptions);
        jPanelAppOptions.setLayout(jPanelAppOptionsLayout);
        jPanelAppOptionsLayout.setHorizontalGroup(
            jPanelAppOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbLoadPassengers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbSaveNetwork, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelAppOptionsLayout.setVerticalGroup(
            jPanelAppOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAppOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbLoadPassengers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSaveNetwork)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAppLayout = new javax.swing.GroupLayout(jPanelApp);
        jPanelApp.setLayout(jPanelAppLayout);
        jPanelAppLayout.setHorizontalGroup(
            jPanelAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAppLayout.createSequentialGroup()
                .addContainerGap(458, Short.MAX_VALUE)
                .addComponent(jPanelAppOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelAppLayout.setVerticalGroup(
            jPanelAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAppLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAppOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jPanelAppOptions.getAccessibleContext().setAccessibleName("");

        JTabbedPane.addTab("Network", jPanelApp);

        jPanelConnectionsAdd.setBorder(javax.swing.BorderFactory.createTitledBorder("Connection Manager & Information"));

        jbConnectionAdd.setText("Add");
        jbConnectionAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConnectionAddActionPerformed(evt);
            }
        });

        jbConnectionShortest.setText("Shortest Path");
        jbConnectionShortest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConnectionShortestActionPerformed(evt);
            }
        });

        jbConnectionPrice.setText("Calculate Price");
        jbConnectionPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConnectionPriceActionPerformed(evt);
            }
        });

        jcbConnectionPriceType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Distance", "Time", "Money" }));

        jLabel15.setText("Station 1");

        jLabel17.setText("Station 2");

        javax.swing.GroupLayout jPanelConnectionsAddLayout = new javax.swing.GroupLayout(jPanelConnectionsAdd);
        jPanelConnectionsAdd.setLayout(jPanelConnectionsAddLayout);
        jPanelConnectionsAddLayout.setHorizontalGroup(
            jPanelConnectionsAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConnectionsAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConnectionsAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelConnectionsAddLayout.createSequentialGroup()
                        .addComponent(jcbConnectionPriceType, 0, 126, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbConnectionPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbConnectionShortest))
                    .addGroup(jPanelConnectionsAddLayout.createSequentialGroup()
                        .addComponent(jcbConnectionS1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbConnectionS2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbConnectionAdd)))
                .addGap(143, 143, 143))
            .addGroup(jPanelConnectionsAddLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel15)
                .addGap(152, 152, 152)
                .addComponent(jLabel17)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelConnectionsAddLayout.setVerticalGroup(
            jPanelConnectionsAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConnectionsAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConnectionsAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConnectionsAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbConnectionS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbConnectionS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConnectionAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConnectionsAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbConnectionPriceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConnectionPrice)
                    .addComponent(jbConnectionShortest))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelConnectionsLayout = new javax.swing.GroupLayout(jPanelConnections);
        jPanelConnections.setLayout(jPanelConnectionsLayout);
        jPanelConnectionsLayout.setHorizontalGroup(
            jPanelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConnectionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelConnectionsAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelConnectionsLayout.setVerticalGroup(
            jPanelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConnectionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelConnectionsAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Connections", jPanelConnections);

        jPanelStationsOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        jButtonStationsPrintConsole.setText("Print Console");
        jButtonStationsPrintConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStationsPrintConsoleActionPerformed(evt);
            }
        });

        jbSaveStations.setText("Save Stations");
        jbSaveStations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveStationsActionPerformed(evt);
            }
        });

        jButtonNewStation.setText("New Station");
        jButtonNewStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewStationActionPerformed(evt);
            }
        });

        jbStationLines.setText("Station Lines");
        jbStationLines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStationLinesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStationsOptionsLayout = new javax.swing.GroupLayout(jPanelStationsOptions);
        jPanelStationsOptions.setLayout(jPanelStationsOptionsLayout);
        jPanelStationsOptionsLayout.setHorizontalGroup(
            jPanelStationsOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStationsOptionsLayout.createSequentialGroup()
                .addGroup(jPanelStationsOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStationsOptionsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonStationsPrintConsole))
                    .addGroup(jPanelStationsOptionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelStationsOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNewStation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSaveStations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbStationLines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelStationsOptionsLayout.setVerticalGroup(
            jPanelStationsOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStationsOptionsLayout.createSequentialGroup()
                .addComponent(jButtonStationsPrintConsole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNewStation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSaveStations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbStationLines)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanelStationsEdit.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit Station"));

        jButtonStationsEdit.setText("OK");
        jButtonStationsEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStationsEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStationsEditLayout = new javax.swing.GroupLayout(jPanelStationsEdit);
        jPanelStationsEdit.setLayout(jPanelStationsEditLayout);
        jPanelStationsEditLayout.setHorizontalGroup(
            jPanelStationsEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStationsEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxStations, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonStationsEdit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelStationsEditLayout.setVerticalGroup(
            jPanelStationsEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStationsEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStationsEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStationsEdit)
                    .addComponent(jComboBoxStations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelStationsLayout = new javax.swing.GroupLayout(jPanelStations);
        jPanelStations.setLayout(jPanelStationsLayout);
        jPanelStationsLayout.setHorizontalGroup(
            jPanelStationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStationsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelStationsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelStationsOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanelStationsLayout.setVerticalGroup(
            jPanelStationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStationsLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanelStationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelStationsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelStationsOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133))
        );

        JTabbedPane.addTab("Stations", jPanelStations);

        jPanelPassengersOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        jButtonPassengersPrintConsole.setText("Print Console");
        jButtonPassengersPrintConsole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPassengersPrintConsoleActionPerformed(evt);
            }
        });

        jbSavePassengers.setText("Save Passengers");
        jbSavePassengers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSavePassengersActionPerformed(evt);
            }
        });

        jButtonNewPassenger.setText("New Passenger");
        jButtonNewPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewPassengerActionPerformed(evt);
            }
        });

        jButtonNearStation.setText("Near Station");
        jButtonNearStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNearStationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPassengersOptionsLayout = new javax.swing.GroupLayout(jPanelPassengersOptions);
        jPanelPassengersOptions.setLayout(jPanelPassengersOptionsLayout);
        jPanelPassengersOptionsLayout.setHorizontalGroup(
            jPanelPassengersOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPassengersOptionsLayout.createSequentialGroup()
                .addGroup(jPanelPassengersOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPassengersOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelPassengersOptionsLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jButtonPassengersPrintConsole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelPassengersOptionsLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jbSavePassengers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelPassengersOptionsLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButtonNearStation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelPassengersOptionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonNewPassenger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelPassengersOptionsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonNewPassenger, jButtonPassengersPrintConsole, jbSavePassengers});

        jPanelPassengersOptionsLayout.setVerticalGroup(
            jPanelPassengersOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPassengersOptionsLayout.createSequentialGroup()
                .addComponent(jButtonPassengersPrintConsole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNewPassenger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSavePassengers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNearStation)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanelPassengersOptionsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonNewPassenger, jButtonPassengersPrintConsole, jbSavePassengers});

        jPanelPassengersEdit.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit Passenger"));

        jButtonPassengerEdit.setText("OK");
        jButtonPassengerEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPassengerEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPassengersEditLayout = new javax.swing.GroupLayout(jPanelPassengersEdit);
        jPanelPassengersEdit.setLayout(jPanelPassengersEditLayout);
        jPanelPassengersEditLayout.setHorizontalGroup(
            jPanelPassengersEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPassengersEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPassengerEdit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPassengersEditLayout.setVerticalGroup(
            jPanelPassengersEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPassengersEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPassengersEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPassengerEdit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPassengersLayout = new javax.swing.GroupLayout(jPanelPassengers);
        jPanelPassengers.setLayout(jPanelPassengersLayout);
        jPanelPassengersLayout.setHorizontalGroup(
            jPanelPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPassengersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPassengersEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPassengersOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanelPassengersLayout.setVerticalGroup(
            jPanelPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPassengersLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelPassengersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPassengersEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPassengersOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Passengers", jPanelPassengers);

        javax.swing.GroupLayout drawPanel1Layout = new javax.swing.GroupLayout(drawPanel1);
        drawPanel1.setLayout(drawPanel1Layout);
        drawPanel1Layout.setHorizontalGroup(
            drawPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );
        drawPanel1Layout.setVerticalGroup(
            drawPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelMapLayout = new javax.swing.GroupLayout(jPanelMap);
        jPanelMap.setLayout(jPanelMapLayout);
        jPanelMapLayout.setHorizontalGroup(
            jPanelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMapLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(drawPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelMapLayout.setVerticalGroup(
            jPanelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drawPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JTabbedPane.addTab("Map", jPanelMap);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewPassengerActionPerformed
        jDialogNewPassenger.setVisible(true);
    }//GEN-LAST:event_jButtonNewPassengerActionPerformed

    private void jbSavePassengersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSavePassengersActionPerformed
        this.network.savePassengers(".//data//passengers.txt");
    }//GEN-LAST:event_jbSavePassengersActionPerformed

    private void jbLoadPassengersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoadPassengersActionPerformed
        
        this.network.loadPassengers(".//data//passengers.txt");
        jButtonPassengersPrintConsole.setEnabled(true);
        jbSavePassengers.setEnabled(true);
        jButtonNearStation.setEnabled(true);
        jComboBoxPassengers.setEnabled(true);
        jButtonPassengerEdit.setEnabled(true);
        
        for (Integer id : this.network.getPassengersST().keys()) {
            Passenger aux = this.network.getPassengersST().get(id);
            jComboBoxPassengers.addItem(""+aux.getId());
        }
        jbLoadPassengers.setEnabled(false);
        
        JOptionPane.showMessageDialog(rootPane, "Passengers loaded with success!");
    }//GEN-LAST:event_jbLoadPassengersActionPerformed

    private void jButtonCreatePassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreatePassengerActionPerformed
        int id = Integer.parseInt(tfPassengerAddId.getText());
        String name = tfPassengerAddName.getText();
        String birthdate_string = tfPassengerAddBirthdate.getText();
        String coord_string = tfPassengerAddPosition.getText();
        String[] coord = coord_string.split("\\;");
        double balance = Double.parseDouble(tfPassengerAddBalance.getText());
        
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date birthdate = null;
        try {
            birthdate = (Date) df.parse(birthdate_string);
        } catch (ParseException ex) {
            Logger.getLogger(Network.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Passenger p = new Passenger(id, name, birthdate, balance, Double.parseDouble(coord[0]), Double.parseDouble(coord[1]));
        this.network.addPassenger(p);
        jComboBoxPassengers.addItem(""+p.getId());
        drawPanel1.repaint();
        
    }//GEN-LAST:event_jButtonCreatePassengerActionPerformed

    private void jButtonPassengersPrintConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPassengersPrintConsoleActionPerformed
       this.network.printPassengers();
    }//GEN-LAST:event_jButtonPassengersPrintConsoleActionPerformed

    private void jButtonPassengerEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPassengerEditActionPerformed
        
        int combo_id = Integer.parseInt((String)jComboBoxPassengers.getSelectedItem().toString());
        Passenger aux = this.network.getPassengersST().get(combo_id);
        tfPassengerEditId.setText(String.valueOf(aux.getId()));
        tfPassengerEditName.setText(aux.getName());
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String birthdate = sdf.format(aux.getBirthdate());
        tfPassengerEditBirthdate.setText(birthdate);
        tfPassengerEditPosition.setText(aux.getPosition().getLatitude()+";"+aux.getPosition().getLongitude());
        tfPassengerEditBalance.setText(String.valueOf(aux.getBalance()));
        
        jDialogEditPassenger.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        jDialogEditPassenger.setModal(true);
        jDialogEditPassenger.setVisible(true);
    }//GEN-LAST:event_jButtonPassengerEditActionPerformed

    private void jButtonEditPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditPassengerActionPerformed
        int combo_id = Integer.parseInt((String)jComboBoxPassengers.getSelectedItem().toString());
        Passenger aux = this.network.getPassengersST().get(combo_id);
        
        int id = Integer.parseInt(tfPassengerEditId.getText());
        aux.setId(id);
        
        String name = tfPassengerEditName.getText();
        aux.setName(name);
 
        String coord_string = tfPassengerEditPosition.getText();
        String[] coord = coord_string.split("\\;");
        
        aux.setPosition(new Coordinate(Double.parseDouble(coord[0]), Double.parseDouble(coord[1])));
        
        String birthdate_string = tfPassengerEditBirthdate.getText();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date birthdate = null;
        try {
            birthdate = (Date) df.parse(birthdate_string);
        } catch (ParseException ex) {
            Logger.getLogger(Network.class.getName()).log(Level.SEVERE, null, ex);
        }      
        aux.setBirthdate(birthdate);
        
        double balance = Double.parseDouble(tfPassengerEditBalance.getText());
        aux.setBalance(balance);
         
        JOptionPane.showMessageDialog(jDialogEditPassenger, "Passenger added with success!");
    }//GEN-LAST:event_jButtonEditPassengerActionPerformed

    private void jButtonStationsPrintConsoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStationsPrintConsoleActionPerformed
        this.network.printStations();

    }//GEN-LAST:event_jButtonStationsPrintConsoleActionPerformed

    private void jbSaveStationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveStationsActionPerformed
        this.network.saveStations(".//data//binary//stations.txt",1);
        /*if(!SAVE_BINARY) {
            this.network.saveStations(".//data//stations_2.txt",0);
        } else {
            this.network.saveStations(".//data//binary//stations.txt",1);
        }*/
        
    }//GEN-LAST:event_jbSaveStationsActionPerformed

    private void jButtonNewStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewStationActionPerformed
        tfStationId.setText(String.valueOf(Network.countStationID));
        tfStationName.setText("");
        tfStationZone.setText("");
        tfStationPosition.setText("");
        tfStationId.setEnabled(false);
        
        jButtonStationAddEdit.setText("Create");
        jDialogStation.setVisible(true); 
    }//GEN-LAST:event_jButtonNewStationActionPerformed

    private void jButtonStationsEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStationsEditActionPerformed
        jButtonStationAddEdit.setText("Edit");
        
        Item item = (Item)jComboBoxStations.getSelectedItem();
        int combo_id = item.getId();
        
        Station aux = this.network.getStationsST().get(combo_id);
        tfStationId.setText(String.valueOf(aux.getId()));
        tfStationName.setText(aux.getName());
        tfStationZone.setText(aux.getZone());
        tfStationPosition.setText(aux.getCoords().getLatitude()+";"+aux.getCoords().getLongitude());
        
        jDialogStation.setVisible(true);
    }//GEN-LAST:event_jButtonStationsEditActionPerformed

    private void jButtonStationAddEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStationAddEditActionPerformed
        // TODO add your handling code here:
        String type = jButtonStationAddEdit.getText();
        if(type.compareToIgnoreCase("create") == 0) {
            //create new
            int id = Integer.parseInt(tfStationId.getText());
            String name = tfStationName.getText();
            String zone = tfStationZone.getText();
            String coord_string = tfStationPosition.getText();
            String[] coord = coord_string.split("\\;");
           
            Station s = new Station(id, name, zone, Double.parseDouble(coord[0]), Double.parseDouble(coord[1]));
            this.network.getStationsST().put(id, s);
            Network.countStationID++;
            this.cb_stations.addElement(new Item(s.getId(), s.getName()));
            
            jComboBoxStations.repaint();
            jcbConnectionS1.repaint();
            jcbConnectionS2.repaint();
            
            JOptionPane.showMessageDialog(jDialogStation, "Station added with success!");
        } else {
            //edit
            Item item = (Item)jComboBoxStations.getSelectedItem();
            int combo_id = item.getId();
            
            Station aux = this.network.getStationsST().get(combo_id);

            String name = tfStationName.getText();
            aux.setName(name);
            
            String zone = tfStationZone.getText();
            aux.setZone(zone);

            String coord_string = tfStationPosition.getText();
            String[] coord = coord_string.split("\\;");

            aux.setCoords(new Coordinate(Double.parseDouble(coord[0]), Double.parseDouble(coord[1])));

            JOptionPane.showMessageDialog(jDialogStation, "Station edited with success!");
        }
        drawPanel1.repaint();
    }//GEN-LAST:event_jButtonStationAddEditActionPerformed

    private void jButtonNearStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNearStationActionPerformed

        int id = Integer.parseInt(jComboBoxPassengers.getSelectedItem().toString());
        JOptionPane.showMessageDialog(rootPane, this.network.findNearestStation(id).toString());
        
    }//GEN-LAST:event_jButtonNearStationActionPerformed

    private void jbStationLinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStationLinesActionPerformed

        Item item = (Item)jComboBoxStations.getSelectedItem();
        int id = item.getId();
        
        String s = new String();
        s = s.concat("Lines in " + this.network.getStationsST().get(id).getName() + ":\n\n");
        ArrayList<Line> lines = this.network.getLinesInStation(id);
        for (Line l : lines) {
            s = s.concat("Line " + l.getName() + "\n");
        }
        JOptionPane.showMessageDialog(rootPane, s);
        
    }//GEN-LAST:event_jbStationLinesActionPerformed

    private void jbConnectionAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConnectionAddActionPerformed
        // TODO add your handling code here:
        Item item = (Item)jcbConnectionS1.getSelectedItem();
        Item item2 = (Item)jcbConnectionS2.getSelectedItem();
        int s1_id = item.getId();
        int s2_id = item2.getId();
        
        Station s1 = this.network.getStationsST().get(s1_id);
        Station s2 = this.network.getStationsST().get(s2_id);
        
        double distance = UsefullFunctions.HaversineInM(s1.getCoords().getLatitude(), s1.getCoords().getLongitude(), s2.getCoords().getLatitude(), s2.getCoords().getLongitude());
        double time = UsefullFunctions.CalculateTimeDistance(distance, 650);
        double price = UsefullFunctions.CalculatePriceDistance(distance, 0.21);
        Connection con = new Connection(s1_id, s2_id, distance, time, price);
        
        this.network.addEdge(con);
        
        JOptionPane.showMessageDialog(rootPane, "Added a connection between " + s1.getName() + " and " + s2.getName());
        
    }//GEN-LAST:event_jbConnectionAddActionPerformed

    private void jbConnectionShortestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConnectionShortestActionPerformed
        // TODO add your handling code here:
        Item item = (Item)jcbConnectionS1.getSelectedItem();
        Item item2 = (Item)jcbConnectionS2.getSelectedItem();
        int s1_id = item.getId();
        int s2_id = item2.getId();
        
        JOptionPane.showMessageDialog(rootPane, this.network.shortestPath(this.network, s1_id,s2_id));
    }//GEN-LAST:event_jbConnectionShortestActionPerformed

    private void jbSaveNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveNetworkActionPerformed
        // TODO add your handling code here:
        this.network.saveNetwork(this.network, ".//data//network_saved.txt", false);
        
        JOptionPane.showMessageDialog(rootPane, "Network saved with success!");
    }//GEN-LAST:event_jbSaveNetworkActionPerformed

    private void jbConnectionPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConnectionPriceActionPerformed
        // TODO add your handling code here:
        Item item = (Item)jcbConnectionS1.getSelectedItem();
        Item item2 = (Item)jcbConnectionS2.getSelectedItem();
        int s1_id = item.getId();
        int s2_id = item2.getId();
        
        String type = jcbConnectionPriceType.getSelectedItem().toString().toUpperCase();
        JOptionPane.showMessageDialog(rootPane, this.network.calculatePrice(this.network, s1_id,s2_id, type));
    }//GEN-LAST:event_jbConnectionPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppMainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppMainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTabbedPane;
    private edu.ufp.inf.lp2.project.gui.DrawPanel drawPanel1;
    private javax.swing.JButton jButtonCreatePassenger;
    private javax.swing.JButton jButtonEditPassenger;
    private javax.swing.JButton jButtonNearStation;
    private javax.swing.JButton jButtonNewPassenger;
    private javax.swing.JButton jButtonNewStation;
    private javax.swing.JButton jButtonPassengerEdit;
    private javax.swing.JButton jButtonPassengersPrintConsole;
    private javax.swing.JButton jButtonStationAddEdit;
    private javax.swing.JButton jButtonStationsEdit;
    private javax.swing.JButton jButtonStationsPrintConsole;
    private javax.swing.JComboBox<String> jComboBoxPassengers;
    private javax.swing.JComboBox<String> jComboBoxStations;
    private javax.swing.JDialog jDialogEditPassenger;
    private javax.swing.JDialog jDialogNewPassenger;
    private javax.swing.JDialog jDialogStation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelApp;
    private javax.swing.JPanel jPanelAppOptions;
    private javax.swing.JPanel jPanelConnections;
    private javax.swing.JPanel jPanelConnectionsAdd;
    private javax.swing.JPanel jPanelMap;
    private javax.swing.JPanel jPanelPassengers;
    private javax.swing.JPanel jPanelPassengersEdit;
    private javax.swing.JPanel jPanelPassengersOptions;
    private javax.swing.JPanel jPanelStations;
    private javax.swing.JPanel jPanelStationsEdit;
    private javax.swing.JPanel jPanelStationsOptions;
    private javax.swing.JButton jbConnectionAdd;
    private javax.swing.JButton jbConnectionPrice;
    private javax.swing.JButton jbConnectionShortest;
    private javax.swing.JButton jbLoadPassengers;
    private javax.swing.JButton jbSaveNetwork;
    private javax.swing.JButton jbSavePassengers;
    private javax.swing.JButton jbSaveStations;
    private javax.swing.JButton jbStationLines;
    private javax.swing.JComboBox<String> jcbConnectionPriceType;
    private javax.swing.JComboBox<String> jcbConnectionS1;
    private javax.swing.JComboBox<String> jcbConnectionS2;
    private javax.swing.JTextField tfPassengerAddBalance;
    private javax.swing.JTextField tfPassengerAddBirthdate;
    private javax.swing.JTextField tfPassengerAddId;
    private javax.swing.JTextField tfPassengerAddName;
    private javax.swing.JTextField tfPassengerAddPosition;
    private javax.swing.JTextField tfPassengerEditBalance;
    private javax.swing.JTextField tfPassengerEditBirthdate;
    private javax.swing.JTextField tfPassengerEditId;
    private javax.swing.JTextField tfPassengerEditName;
    private javax.swing.JTextField tfPassengerEditPosition;
    private javax.swing.JTextField tfStationId;
    private javax.swing.JTextField tfStationName;
    private javax.swing.JTextField tfStationPosition;
    private javax.swing.JTextField tfStationZone;
    // End of variables declaration//GEN-END:variables

    public static Network getNetwork() {
        return network;
    }

    public static void setNetwork(Network network) {
        AppMainJFrame.network = network;
    }
    
}

class Item
{
    private int id;
    private String text;

    public Item(int id, String text)
    {
        this.id = id;
        this.text = text;
    }

    public int getId()
    {
        return id;
    }

    public String getText()
    {
        return text;
    }

    public String toString()
    {
        return text;
    }
}